apiVersion: v1
kind: Service
metadata:
  name: local-mysql-fiap-car-store
  namespace: fiap-car-store
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: local-mysql-fiap-car-store
