kind: Service
apiVersion: v1
metadata:
  name: fiap-car-store-api
  namespace: fiap-car-store
spec:
  selector:
    app: fiap-car-store-api
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32000