apiVersion: batch/v1
kind: Job
metadata:
  name: fiap-car-store-migration
  namespace: fiap-car-store
spec:
  template:
    spec:
      containers:
      - name: fiap-car-store-migration
        image: fiap-car-store_service-migration:latest
        imagePullPolicy: IfNotPresent
        envFrom:
          - secretRef:
              name: fiap-car-store-secret
          - configMapRef:
              name: fiap-car-store-config
      restartPolicy: OnFailure
