apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiap-car-store-api
  namespace: fiap-car-store
  labels:
    app: fiap-car-store-api
spec:
  selector:
    matchLabels:
      app: fiap-car-store-api
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  revisionHistoryLimit: 10
  template:
    metadata:
      name: fiap-car-store-api
      namespace: fiap-car-store
      labels:
        app: fiap-car-store-api
        version: "latest"
    spec:
      containers:
        - name: fiap-car-store-api
          image: fiap-car-store_service-fiap-car-store-api:latest
          livenessProbe:
            httpGet:
              path: /health-check
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 5
          resources:
            limits:
              memory: "512Mi"
            requests:
              memory: "256Mi"
          imagePullPolicy: "IfNotPresent"
          ports:
          - containerPort: 3000
          envFrom:
          - secretRef:
              name: fiap-car-store-secret
          - configMapRef:
              name: fiap-car-store-config
